sudo: false
language: node_js
node_js:
- stable
branches:
  only:
  - main
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script: 'true'
- npm test
- npm run coveralls
